//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorVotos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracao
    {
        public int ID { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public int Navegadores { get; set; }
        public int VotosPorNavegador { get; set; }
        public string SenhaPadrao { get; set; }
    }
}
